*** Jour 10 : Hoof It ***
Vous arrivez tous à une usine de production de lave sur une île flottante dans le ciel. Alors que les autres commencent à fouiller l'immense complexe industriel, vous sentez un petit nez vous frapper la jambe et baissez les yeux pour découvrir un renne portant un casque de sécurité.

Le renne tient un livre intitulé « Guide de randonnée de l'île de lave ». Cependant, lorsque vous ouvrez le livre, vous découvrez que la majeure partie de celui-ci semble avoir été brûlée par la lave ! Alors que vous êtes sur le point de demander comment vous pouvez aider, le renne vous apporte une carte topographique vierge des environs (votre contribution au puzzle) et vous regarde avec enthousiasme.

Peut-être pouvez-vous aider à combler les sentiers de randonnée manquants ?

La carte topographique indique la hauteur de chaque position à l'aide d'une échelle allant du 0plus bas au 9plus haut. Par exemple :

0123
1234
8765
9876
En vous basant sur des fragments non brûlés du livre, vous déterminez qu'un bon sentier de randonnée est aussi long que possible et présente une pente ascendante régulière et progressive . À toutes fins pratiques, cela signifie qu'un sentier de randonnée est tout chemin qui commence à la hauteur 0, se termine à la hauteur 9et augmente toujours d'une hauteur d'exactement 1 à chaque pas. Les sentiers de randonnée ne comprennent jamais de marches diagonales - uniquement vers le haut, vers le bas, vers la gauche ou vers la droite (du point de vue de la carte).

Vous levez les yeux de la carte et remarquez que le renne a gentiment commencé à construire une petite pile de crayons, de marqueurs, de règles, de compas, d'autocollants et d'autres équipements dont vous pourriez avoir besoin pour mettre à jour la carte avec les sentiers de randonnée.

Un point de départ est une position qui démarre un ou plusieurs sentiers de randonnée. Ici, ces positions auront toujours une hauteur de . En assemblant plusieurs fragments de pages, vous établissez que le score0 d'un point de départ est le nombre de positions de hauteur accessibles à partir de ce point de départ via un sentier de randonnée. Dans l'exemple ci-dessus, le point de départ unique dans le coin supérieur gauche a un score de car il peut atteindre un seul point (celui en bas à gauche).919

Ce point de départ a un score de 2:

...0...
...1...
...2...
6543456
7.....7
8.....8
9.....9
(Les positions marquées .sont des tuiles infranchissables pour simplifier ces exemples ; elles n'apparaissent pas sur votre carte topographique réelle.)

Ce point de départ de sentier a un score de 4parce que chaque point 9est accessible par un sentier de randonnée, sauf celui immédiatement à gauche du point de départ du sentier :

..90..9
...1.98
...2..7
6543456
765.987
876....
987....
Cette carte topographique contient deux points de départ de sentiers ; le point de départ du sentier en haut a un score de 1, tandis que le point de départ du sentier en bas a un score de 2:

10..9..
2...8..
3...7..
4567654
...8..3
...9..2
.....01
Voici un exemple plus grand :

89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
Cet exemple plus grand comporte 9 points de départ. En considérant les points de départ dans l'ordre de lecture, ils ont des scores de 5, 6, 5, 3, 1, 3, 5, 3, et 5. En additionnant ces scores, la somme des scores de tous les points de départ est 36.

Le renne porte joyeusement un rapporteur et l'ajoute à la pile. Quelle est la somme des scores de tous les points de départ des sentiers sur votre carte topographique ?


** Deuxième partie **
Le renne passe quelques minutes à examiner votre carte de sentier de randonnée avant de se rendre compte de quelque chose, de disparaître pendant quelques minutes et de revenir enfin avec un autre morceau de papier légèrement carbonisé.

L'article décrit une deuxième façon de mesurer un point de départ de sentier, appelée son classement . Le classement d'un point de départ de sentier correspond au nombre de sentiers de randonnée distincts qui commencent à ce point de départ. Par exemple :

.....0.
..4321.
..5..2.
..6543.
..7..4.
..8765.
..9....
La carte ci-dessus présente un seul point de départ de sentier ; sa classification est 3due au fait qu'il existe exactement trois sentiers de randonnée distincts qui commencent à cet endroit :

.....0.   .....0.   .....0.
..4321.   .....1.   .....1.
..5....   .....2.   .....2.
..6....   ..6543.   .....3.
..7....   ..7....   .....4.
..8....   ..8....   ..8765.
..9....   ..9....   ..9....
Voici une carte contenant un seul point de départ de sentier avec une cote 13:

..90..9
...1.98
...2..7
6543456
765.987
876....
987....
Cette carte contient un seul point de départ de sentier avec une cote 227(car il existe 121des sentiers de randonnée distincts qui mènent au 9bord droit et 106qui mènent au 9bord inférieur) :

012345
123456
234567
345678
4.6789
56789.
Voici le plus grand exemple précédent :

89010123
78121874
87430965
96549874
45678903
32019012
01329801
10456732
En considérant les points de départ des sentiers dans l'ordre de lecture, ils ont des cotes de 20, 24, 10, 4, 1, 4, 5, 8, et 5. La somme de toutes les cotes des points de départ des sentiers dans cet exemple de carte topographique plus grand est 81.

Vous ne savez pas comment, mais le renne semble avoir fabriqué de minuscules drapeaux à partir de cure-dents et de morceaux de papier et les utilise pour marquer les points de départ des sentiers sur votre carte topographique. Quelle est la somme des notes de tous les points de départ des sentiers ?
