*** Jour 7 : Réparation du pont ***
Les historiens vous emmènent vers un pont de corde familier au-dessus d'une rivière au milieu d'une jungle. Le chef n'est pas de ce côté du pont, mais peut-être est-il de l'autre côté ?

Lorsque vous vous apprêtez à traverser le pont, vous remarquez un groupe d'ingénieurs qui tentent de le réparer. (Apparemment, il tombe en panne assez fréquemment.) Vous ne pourrez pas traverser tant qu'il ne sera pas réparé.

Vous demandez combien de temps cela va prendre ; les ingénieurs vous disent qu'il ne faut que des étalonnages finaux, mais de jeunes éléphants jouaient à proximité et ont volé tous les opérateurs de leurs équations d'étalonnage ! Ils pourraient terminer les étalonnages si seulement quelqu'un pouvait déterminer quelles valeurs de test pourraient éventuellement être produites en plaçant n'importe quelle combinaison d'opérateurs dans leurs équations d'étalonnage (votre entrée de puzzle).

Par exemple:

190: 10 19
3267: 81 40 27
83: 17 5
156: 15 6
7290: 6 8 6 15
161011: 16 10 13
192: 17 8 14
21037: 9 7 18 13
292: 11 6 16 20
Chaque ligne représente une équation unique. La valeur de test apparaît avant les deux points sur chaque ligne ; il vous incombe de déterminer si les nombres restants peuvent être combinés avec des opérateurs pour produire la valeur de test.

Les opérateurs sont toujours évalués de gauche à droite , et non selon les règles de priorité. De plus, les nombres dans les équations ne peuvent pas être réorganisés. En jetant un œil dans la jungle, vous pouvez voir des éléphants tenant deux types d'opérateurs différents : additionner ( +) et multiplier ( *).

Seules trois des équations ci-dessus peuvent être rendues vraies en insérant des opérateurs :

190: 10 19n'a qu'une seule position qui accepte un opérateur : entre 10et 19. Choisir +donnerait 29, mais choisir *donnerait la valeur de test ( 10 * 19 = 190).
3267: 81 40 27a deux positions pour les opérateurs. Parmi les quatre configurations possibles des opérateurs, deux font correspondre le côté droit à la valeur de test : 81 + 40 * 27et 81 * 40 + 27les deux sont égaux 3267(lorsqu'ils sont évalués de gauche à droite) !
292: 11 6 16 20peut être résolu d'une seule manière exactement : 11 + 6 * 16 + 20.
Les ingénieurs ont simplement besoin du résultat total de l'étalonnage , qui est la somme des valeurs de test des seules équations qui pourraient être vraies. Dans l'exemple ci-dessus, la somme des valeurs de test pour les trois équations répertoriées ci-dessus est 3749.

Déterminer quelles équations pourraient être vraies. Quel est leur résultat d'étalonnage total ?


** Deuxième partie **
Les ingénieurs semblent inquiets : le résultat d'étalonnage total que vous leur avez donné est loin d'être dans les limites de sécurité. C'est alors que vous repérez votre erreur : des éléphants bien cachés détiennent un troisième type d'opérateur .

L' opérateur de concaténation|| ( ) combine les chiffres de ses entrées gauche et droite en un seul nombre. Par exemple, 12 || 345deviendrait 12345. Tous les opérateurs sont toujours évalués de gauche à droite.

Maintenant, en plus des trois équations qui pourraient être rendues vraies en utilisant uniquement l'addition et la multiplication, l'exemple ci-dessus comporte trois autres équations qui peuvent être rendues vraies en insérant des opérateurs :

156: 15 6peut être rendu vrai par une seule concaténation : 15 || 6 = 156.
7290: 6 8 6 15peut être rendu vrai en utilisant 6 * 8 || 6 * 15.
192: 17 8 14peut être rendu vrai en utilisant 17 || 8 + 14.
L'addition des six valeurs de test (les trois qui pouvaient être réalisées auparavant en utilisant uniquement +et *plus les trois nouvelles qui peuvent maintenant être réalisées en utilisant également ||) produit le nouveau résultat d'étalonnage total de 11387.

En utilisant vos nouvelles connaissances sur les cachettes des éléphants, déterminez quelles équations pourraient être vraies. Quel est leur résultat d'étalonnage total ?
